### ISSUE TITLE
Why  Antlr ot Xtext?

### ISSUE THREAD

**Issue by MaSven** [mouellet/vaadin-java-dsl#1]
My Question is why not generate this ? Now you have to write a wrapper for each method if you want to complete it. With Xtext you can even get autocomplete for the new DSL. 

Iam just a student that want to know what is the benifit of doing it this way.

**Comment by mouellet** [comment]
Hi @MaSven, thanks for your interest in this library!

I didn't want to write those wrapper method manually so I wrote code generators (take a look at the `org.vaadin.addons.dsl.support` package). This way I can regenerate then on the fly when a new Vaadin version comes out and compare changes in the components api. There's some issues with the component hierarchy, but I still hope to have it fully automated.

I don't know Xtext.. There could be better ways to do this! I started this after reading Martin Fowler's book on DSL (https://martinfowler.com/books/dsl.html). I design this based on his nested function pattern.
